-- ============================================================
-- HINCH.AR — Seed de eventos 2025
-- Liga Profesional Fechas 14-16
-- Copa Libertadores Fechas 1-6 (solo locales argentinos)
-- Copa Sudamericana Fechas 1-6 (solo locales argentinos)
-- ============================================================

INSERT INTO events (type, title, subtitle, venue_name, venue_address, venue_city, venue_province, event_date, home_team, away_team, competition, tags, is_active, is_featured, external_id)
VALUES

-- ================== LIGA PROFESIONAL — FECHA 14 ==================
('partido','Belgrano vs Aldosivi','Liga Profesional — Fecha 14','Estadio Mario Alberto Kempes','Av. Cárcano s/n','Córdoba','Córdoba','2025-04-10T21:00:00-03:00','Belgrano','Aldosivi','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f14_belgrano_aldosivi'),
('partido','Riestra vs Instituto','Liga Profesional — Fecha 14','Estadio Guillermo Laza','Av. Cruz 4435','Buenos Aires','Buenos Aires','2025-04-11T15:00:00-03:00','Riestra','Instituto','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f14_riestra_instituto'),
('partido','Ind. Rivadavia vs Argentinos Jrs','Liga Profesional — Fecha 14','Estadio Bautista Gargantini','Av. San Martín 1600','Mendoza','Mendoza','2025-04-11T15:30:00-03:00','Independiente Rivadavia','Argentinos Juniors','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f14_rivadavia_argentinos'),
('partido','Estudiantes vs Unión','Liga Profesional — Fecha 14','Estadio Jorge Luis Hirschi','Av. 1 y 57','La Plata','Buenos Aires','2025-04-11T17:15:00-03:00','Estudiantes','Unión','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f14_estudiantes_union'),
('partido','Boca Juniors vs Independiente','Liga Profesional — Fecha 14','Estadio Alberto J. Armando','Brandsen 805','Buenos Aires','Buenos Aires','2025-04-11T19:30:00-03:00','Boca Juniors','Independiente','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f14_boca_independiente'),
('partido','Estudiantes RC vs Barracas Central','Liga Profesional — Fecha 14','Estadio Guillermo Laza','Av. Cruz 4435','Buenos Aires','Buenos Aires','2025-04-11T21:45:00-03:00','Estudiantes RC','Barracas Central','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f14_estudiantesrc_barracas'),
('partido','Newell''s vs San Lorenzo','Liga Profesional — Fecha 14','Estadio Marcelo Bielsa','Av. Carlos Pellegrini 2890','Rosario','Santa Fe','2025-04-12T15:00:00-03:00','Newell''s Old Boys','San Lorenzo','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f14_newells_sanlorenzo'),
('partido','Platense vs Gimnasia Mendoza','Liga Profesional — Fecha 14','Estadio Ciudad de Vicente López','Monroe 4601','Buenos Aires','Buenos Aires','2025-04-12T15:00:00-03:00','Platense','Gimnasia Mendoza','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f14_platense_gimnasiamza'),
('partido','Huracán vs Rosario Central','Liga Profesional — Fecha 14','Estadio Tomás Adolfo Ducó','Av. Amancio Alcorta 2884','Buenos Aires','Buenos Aires','2025-04-12T17:30:00-03:00','Huracán','Rosario Central','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f14_huracan_central'),
('partido','Atlético Tucumán vs Tigre','Liga Profesional — Fecha 14','Estadio Monumental José Fierro','Av. Benjamín Aráoz 1000','San Miguel de Tucumán','Tucumán','2025-04-12T17:30:00-03:00','Atlético Tucumán','Tigre','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f14_attucuman_tigre'),
('partido','Racing vs River Plate','Liga Profesional — Fecha 14','Estadio Juan Domingo Perón','Av. Galicia 2070','Avellaneda','Buenos Aires','2025-04-12T20:00:00-03:00','Racing Club','River Plate','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f14_racing_river'),
('partido','Defensa y Justicia vs Talleres','Liga Profesional — Fecha 14','Estadio Norberto Tomaghello','Av. Mitre 3301','Florencio Varela','Buenos Aires','2025-04-13T16:30:00-03:00','Defensa y Justicia','Talleres','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f14_defensa_talleres'),
('partido','Sarmiento vs Gimnasia LP','Liga Profesional — Fecha 14','Estadio Eva Perón','Hipólito Yrigoyen 1400','Junín','Buenos Aires','2025-04-13T16:30:00-03:00','Sarmiento','Gimnasia La Plata','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f14_sarmiento_gimnasia'),
('partido','Lanús vs Banfield','Liga Profesional — Fecha 14','Estadio Ciudad de Lanús','Av. General Paz 399','Lanús','Buenos Aires','2025-04-13T19:00:00-03:00','Lanús','Banfield','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f14_lanus_banfield'),
('partido','Vélez vs Central Córdoba','Liga Profesional — Fecha 14','Estadio José Amalfitani','Av. Juan B. Justo 9200','Buenos Aires','Buenos Aires','2025-04-13T21:30:00-03:00','Vélez Sársfield','Central Córdoba','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f14_velez_centralcba'),

-- ================== LIGA PROFESIONAL — FECHA 15 ==================
('partido','Unión vs Newell''s','Liga Profesional — Fecha 15','Estadio 15 de Abril','San Justo 151','Santa Fe','Santa Fe','2025-04-17T20:30:00-03:00','Unión','Newell''s Old Boys','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f15_union_newells'),
('partido','Gimnasia LP vs Estudiantes RC','Liga Profesional — Fecha 15','Estadio Juan Carlos Zerillo','Av. 44 y 60','La Plata','Buenos Aires','2025-04-18T15:00:00-03:00','Gimnasia La Plata','Estudiantes RC','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f15_gimnasialp_estudiantesrc'),
('partido','Instituto vs Estudiantes LP','Liga Profesional — Fecha 15','Estadio Juan Domingo Perón Alta Córdoba','Av. Colón 5860','Córdoba','Córdoba','2025-04-18T17:15:00-03:00','Instituto','Estudiantes','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f15_instituto_estudiantes'),
('partido','Independiente vs Defensa y Justicia','Liga Profesional — Fecha 15','Estadio Libertadores de América','Av. Mitre 470','Avellaneda','Buenos Aires','2025-04-18T19:30:00-03:00','Independiente','Defensa y Justicia','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f15_independiente_defensa'),
('partido','Argentinos Jrs vs Atlético Tucumán','Liga Profesional — Fecha 15','Estadio Diego Armando Maradona','Boyacá 2345','Buenos Aires','Buenos Aires','2025-04-18T21:45:00-03:00','Argentinos Juniors','Atlético Tucumán','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f15_argentinos_attucuman'),
('partido','Aldosivi vs Racing','Liga Profesional — Fecha 15','Estadio José María Minella','Av. Juan B. Justo 3300','Mar del Plata','Buenos Aires','2025-04-19T13:30:00-03:00','Aldosivi','Racing Club','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f15_aldosivi_racing'),
('partido','River Plate vs Boca Juniors','Liga Profesional — Fecha 15','Estadio Monumental','Av. Figueroa Alcorta 7597','Buenos Aires','Buenos Aires','2025-04-19T17:00:00-03:00','River Plate','Boca Juniors','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f15_river_boca'),
('partido','Rosario Central vs Sarmiento','Liga Profesional — Fecha 15','Estadio Gigante de Arroyito','Av. Torcuato de Alvear 1000','Rosario','Santa Fe','2025-04-19T20:30:00-03:00','Rosario Central','Sarmiento','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f15_central_sarmiento'),
('partido','Talleres vs Riestra','Liga Profesional — Fecha 15','Estadio Mario Alberto Kempes','Av. Cárcano s/n','Córdoba','Córdoba','2025-04-19T20:30:00-03:00','Talleres','Riestra','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f15_talleres_riestra'),
('partido','Barracas Central vs Belgrano','Liga Profesional — Fecha 15','Estadio Claypole','Av. Monteverde 5240','Buenos Aires','Buenos Aires','2025-04-20T15:00:00-03:00','Barracas Central','Belgrano','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f15_barracas_belgrano'),
('partido','Banfield vs Ind. Rivadavia','Liga Profesional — Fecha 15','Estadio Florencio Sola','Av. Presidente Perón 2102','Banfield','Buenos Aires','2025-04-20T17:15:00-03:00','Banfield','Independiente Rivadavia','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f15_banfield_rivadavia'),
('partido','Central Córdoba vs Platense','Liga Profesional — Fecha 15','Estadio Único Madre de Ciudades','Ruta 9 s/n','Santiago del Estero','Santiago del Estero','2025-04-20T17:15:00-03:00','Central Córdoba','Platense','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f15_centralcba_platense'),
('partido','San Lorenzo vs Vélez','Liga Profesional — Fecha 15','Estadio Pedro Bidegain','Av. Perito Moreno 5301','Buenos Aires','Buenos Aires','2025-04-20T19:30:00-03:00','San Lorenzo','Vélez Sársfield','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f15_sanlorenzo_velez'),
('partido','Tigre vs Huracán','Liga Profesional — Fecha 15','Estadio José Dellagiovanna','Av. Vergara 2880','Victoria','Buenos Aires','2025-04-20T21:45:00-03:00','Tigre','Huracán','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f15_tigre_huracan'),
('partido','Gimnasia Mendoza vs Lanús','Liga Profesional — Fecha 15','Estadio Bautista Gargantini','Av. San Martín 1600','Mendoza','Mendoza','2025-04-20T21:45:00-03:00','Gimnasia Mendoza','Lanús','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f15_gimnasiamza_lanus'),

-- ================== LIGA PROFESIONAL — FECHA 16 ==================
('partido','Defensa y Justicia vs Boca Juniors','Liga Profesional — Fecha 16','Estadio Norberto Tomaghello','Av. Mitre 3301','Florencio Varela','Buenos Aires','2025-04-23T20:00:00-03:00','Defensa y Justicia','Boca Juniors','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f16_defensa_boca'),
('partido','Riestra vs Independiente','Liga Profesional — Fecha 16','Estadio Guillermo Laza','Av. Cruz 4435','Buenos Aires','Buenos Aires','2025-04-24T17:00:00-03:00','Riestra','Independiente','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f16_riestra_independiente'),
('partido','Lanús vs Central Córdoba','Liga Profesional — Fecha 16','Estadio Ciudad de Lanús','Av. General Paz 399','Lanús','Buenos Aires','2025-04-24T19:15:00-03:00','Lanús','Central Córdoba','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f16_lanus_centralcba'),
('partido','Estudiantes RC vs Rosario Central','Liga Profesional — Fecha 16','Estadio Guillermo Laza','Av. Cruz 4435','Buenos Aires','Buenos Aires','2025-04-24T19:15:00-03:00','Estudiantes RC','Rosario Central','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f16_estudiantesrc_central'),
('partido','Racing vs Barracas Central','Liga Profesional — Fecha 16','Estadio Juan Domingo Perón','Av. Galicia 2070','Avellaneda','Buenos Aires','2025-04-24T21:30:00-03:00','Racing Club','Barracas Central','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f16_racing_barracas'),
('partido','Platense vs San Lorenzo','Liga Profesional — Fecha 16','Estadio Ciudad de Vicente López','Monroe 4601','Buenos Aires','Buenos Aires','2025-04-25T14:00:00-03:00','Platense','San Lorenzo','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f16_platense_sanlorenzo'),
('partido','Estudiantes LP vs Talleres','Liga Profesional — Fecha 16','Estadio Jorge Luis Hirschi','Av. 1 y 57','La Plata','Buenos Aires','2025-04-25T17:00:00-03:00','Estudiantes','Talleres','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f16_estudiantes_talleres'),
('partido','Sarmiento vs Tigre','Liga Profesional — Fecha 16','Estadio Eva Perón','Hipólito Yrigoyen 1400','Junín','Buenos Aires','2025-04-25T19:15:00-03:00','Sarmiento','Tigre','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f16_sarmiento_tigre'),
('partido','River Plate vs Aldosivi','Liga Profesional — Fecha 16','Estadio Monumental','Av. Figueroa Alcorta 7597','Buenos Aires','Buenos Aires','2025-04-25T21:30:00-03:00','River Plate','Aldosivi','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f16_river_aldosivi'),
('partido','Ind. Rivadavia vs Gimnasia Mendoza','Liga Profesional — Fecha 16','Estadio Bautista Gargantini','Av. San Martín 1600','Mendoza','Mendoza','2025-04-26T15:00:00-03:00','Independiente Rivadavia','Gimnasia Mendoza','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f16_rivadavia_gimnasiamza'),
('partido','Belgrano vs Gimnasia LP','Liga Profesional — Fecha 16','Estadio Mario Alberto Kempes','Av. Cárcano s/n','Córdoba','Córdoba','2025-04-26T17:30:00-03:00','Belgrano','Gimnasia La Plata','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f16_belgrano_gimnasialp'),
('partido','Newell''s vs Instituto','Liga Profesional — Fecha 16','Estadio Marcelo Bielsa','Av. Carlos Pellegrini 2890','Rosario','Santa Fe','2025-04-26T17:30:00-03:00','Newell''s Old Boys','Instituto','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f16_newells_instituto'),
('partido','Atlético Tucumán vs Banfield','Liga Profesional — Fecha 16','Estadio Monumental José Fierro','Av. Benjamín Aráoz 1000','San Miguel de Tucumán','Tucumán','2025-04-26T20:00:00-03:00','Atlético Tucumán','Banfield','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f16_attucuman_banfield'),
('partido','Vélez vs Unión','Liga Profesional — Fecha 16','Estadio José Amalfitani','Av. Juan B. Justo 9200','Buenos Aires','Buenos Aires','2025-04-27T18:45:00-03:00','Vélez Sársfield','Unión','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f16_velez_union'),
('partido','Huracán vs Argentinos Jrs','Liga Profesional — Fecha 16','Estadio Tomás Adolfo Ducó','Av. Amancio Alcorta 2884','Buenos Aires','Buenos Aires','2025-04-27T21:00:00-03:00','Huracán','Argentinos Juniors','Liga Profesional Argentina',ARRAY['fútbol','liga profesional'],true,true,'lpa_f16_huracan_argentinos'),

-- ================== COPA LIBERTADORES — solo locales argentinos ==================
-- Fecha 1
('partido','Ind. Rivadavia vs Bolívar','Copa Libertadores — Fecha 1','Estadio Bautista Gargantini','Av. San Martín 1600','Mendoza','Mendoza','2025-04-07T19:00:00-03:00','Independiente Rivadavia','Bolívar','Copa Libertadores',ARRAY['fútbol','copa libertadores'],true,false,'liber_f1_rivadavia_bolivar'),
('partido','Rosario Central vs IDV','Copa Libertadores — Fecha 1','Estadio Gigante de Arroyito','Av. Torcuato de Alvear 1000','Rosario','Santa Fe','2025-04-09T19:00:00-03:00','Rosario Central','Independiente del Valle','Copa Libertadores',ARRAY['fútbol','copa libertadores'],true,false,'liber_f1_central_idv'),
('partido','Platense vs Corinthians','Copa Libertadores — Fecha 1','Estadio Ciudad de Vicente López','Monroe 4601','Buenos Aires','Buenos Aires','2025-04-09T21:00:00-03:00','Platense','Corinthians','Copa Libertadores',ARRAY['fútbol','copa libertadores'],true,false,'liber_f1_platense_corinthians'),
-- Fecha 2
('partido','Estudiantes vs Cusco FC','Copa Libertadores — Fecha 2','Estadio Jorge Luis Hirschi','Av. 1 y 57','La Plata','Buenos Aires','2025-04-14T19:00:00-03:00','Estudiantes','Cusco FC','Copa Libertadores',ARRAY['fútbol','copa libertadores'],true,false,'liber_f2_estudiantes_cusco'),
('partido','Boca Juniors vs Barcelona SC','Copa Libertadores — Fecha 2','Estadio Alberto J. Armando','Brandsen 805','Buenos Aires','Buenos Aires','2025-04-14T21:00:00-03:00','Boca Juniors','Barcelona SC','Copa Libertadores',ARRAY['fútbol','copa libertadores'],true,false,'liber_f2_boca_barcelonasc'),
('partido','Lanús vs Always Ready','Copa Libertadores — Fecha 2','Estadio Ciudad de Lanús','Av. General Paz 399','Lanús','Buenos Aires','2025-04-16T19:00:00-03:00','Lanús','Always Ready','Copa Libertadores',ARRAY['fútbol','copa libertadores'],true,false,'liber_f2_lanus_alwaysready'),
-- Fecha 3
('partido','Lanús vs LDU Quito','Copa Libertadores — Fecha 3','Estadio Ciudad de Lanús','Av. General Paz 399','Lanús','Buenos Aires','2025-04-28T19:00:00-03:00','Lanús','LDU Quito','Copa Libertadores',ARRAY['fútbol','copa libertadores'],true,false,'liber_f3_lanus_ldu'),
('partido','Platense vs Santa Fe','Copa Libertadores — Fecha 3','Estadio Ciudad de Vicente López','Monroe 4601','Buenos Aires','Buenos Aires','2025-04-29T19:00:00-03:00','Platense','Santa Fe','Copa Libertadores',ARRAY['fútbol','copa libertadores'],true,false,'liber_f3_platense_santafe'),
('partido','Estudiantes vs Flamengo','Copa Libertadores — Fecha 3','Estadio Jorge Luis Hirschi','Av. 1 y 57','La Plata','Buenos Aires','2025-04-29T21:30:00-03:00','Estudiantes','Flamengo','Copa Libertadores',ARRAY['fútbol','copa libertadores'],true,false,'liber_f3_estudiantes_flamengo'),
('partido','Ind. Rivadavia vs La Guaira','Copa Libertadores — Fecha 3','Estadio Bautista Gargantini','Av. San Martín 1600','Mendoza','Mendoza','2025-04-30T19:00:00-03:00','Independiente Rivadavia','La Guaira','Copa Libertadores',ARRAY['fútbol','copa libertadores'],true,false,'liber_f3_rivadavia_laguaira'),
-- Fecha 4
('partido','Rosario Central vs Libertad','Copa Libertadores — Fecha 4','Estadio Gigante de Arroyito','Av. Torcuato de Alvear 1000','Rosario','Santa Fe','2025-05-05T19:00:00-03:00','Rosario Central','Libertad','Copa Libertadores',ARRAY['fútbol','copa libertadores'],true,false,'liber_f4_central_libertad'),
('partido','Ind. Rivadavia vs Fluminense','Copa Libertadores — Fecha 4','Estadio Bautista Gargantini','Av. San Martín 1600','Mendoza','Mendoza','2025-05-06T21:30:00-03:00','Independiente Rivadavia','Fluminense','Copa Libertadores',ARRAY['fútbol','copa libertadores'],true,false,'liber_f4_rivadavia_fluminense'),
('partido','Platense vs Peñarol','Copa Libertadores — Fecha 4','Estadio Ciudad de Vicente López','Monroe 4601','Buenos Aires','Buenos Aires','2025-05-07T19:00:00-03:00','Platense','Peñarol','Copa Libertadores',ARRAY['fútbol','copa libertadores'],true,false,'liber_f4_platense_penarol'),
-- Fecha 5
('partido','Rosario Central vs UCV FC','Copa Libertadores — Fecha 5','Estadio Gigante de Arroyito','Av. Torcuato de Alvear 1000','Rosario','Santa Fe','2025-05-19T19:00:00-03:00','Rosario Central','UCV FC','Copa Libertadores',ARRAY['fútbol','copa libertadores'],true,false,'liber_f5_central_ucvfc'),
('partido','Boca Juniors vs Cruzeiro','Copa Libertadores — Fecha 5','Estadio Alberto J. Armando','Brandsen 805','Buenos Aires','Buenos Aires','2025-05-19T21:30:00-03:00','Boca Juniors','Cruzeiro','Copa Libertadores',ARRAY['fútbol','copa libertadores'],true,false,'liber_f5_boca_cruzeiro'),
-- Fecha 6
('partido','Lanús vs Mirassol','Copa Libertadores — Fecha 6','Estadio Ciudad de Lanús','Av. General Paz 399','Lanús','Buenos Aires','2025-05-26T19:00:00-03:00','Lanús','Mirassol','Copa Libertadores',ARRAY['fútbol','copa libertadores'],true,false,'liber_f6_lanus_mirassol'),
('partido','Estudiantes vs Ind. Medellín','Copa Libertadores — Fecha 6','Estadio Jorge Luis Hirschi','Av. 1 y 57','La Plata','Buenos Aires','2025-05-26T21:30:00-03:00','Estudiantes','Independiente Medellín','Copa Libertadores',ARRAY['fútbol','copa libertadores'],true,false,'liber_f6_estudiantes_indmedellin'),
('partido','Boca Juniors vs U. Católica','Copa Libertadores — Fecha 6','Estadio Alberto J. Armando','Brandsen 805','Buenos Aires','Buenos Aires','2025-05-28T21:30:00-03:00','Boca Juniors','U. Católica','Copa Libertadores',ARRAY['fútbol','copa libertadores'],true,false,'liber_f6_boca_ucatolica'),

-- ================== COPA SUDAMERICANA — solo locales argentinos ==================
-- Fecha 1
('partido','Barracas Central vs Vasco Da Gama','Copa Sudamericana — Fecha 1','Estadio Claypole','Av. Monteverde 5240','Buenos Aires','Buenos Aires','2025-04-07T19:00:00-03:00','Barracas Central','Vasco Da Gama','Copa Sudamericana',ARRAY['fútbol','copa sudamericana'],true,false,'sudamer_f1_barracas_vasco'),
('partido','Riestra vs Palestino','Copa Sudamericana — Fecha 1','Estadio Guillermo Laza','Av. Cruz 4435','Buenos Aires','Buenos Aires','2025-04-08T19:00:00-03:00','Riestra','Palestino','Copa Sudamericana',ARRAY['fútbol','copa sudamericana'],true,false,'sudamer_f1_riestra_palestino'),
-- Fecha 2
('partido','Racing vs Botafogo','Copa Sudamericana — Fecha 2','Estadio Juan Domingo Perón','Av. Galicia 2070','Avellaneda','Buenos Aires','2025-04-15T19:00:00-03:00','Racing Club','Botafogo','Copa Sudamericana',ARRAY['fútbol','copa sudamericana'],true,false,'sudamer_f2_racing_botafogo'),
('partido','River Plate vs Carabobo','Copa Sudamericana — Fecha 2','Estadio Monumental','Av. Figueroa Alcorta 7597','Buenos Aires','Buenos Aires','2025-04-15T21:30:00-03:00','River Plate','Carabobo','Copa Sudamericana',ARRAY['fútbol','copa sudamericana'],true,false,'sudamer_f2_river_carabobo'),
('partido','Tigre vs Macara','Copa Sudamericana — Fecha 2','Estadio José Dellagiovanna','Av. Vergara 2880','Victoria','Buenos Aires','2025-04-16T19:00:00-03:00','Tigre','Macara','Copa Sudamericana',ARRAY['fútbol','copa sudamericana'],true,false,'sudamer_f2_tigre_macara'),
('partido','San Lorenzo vs Dep. Cuenca','Copa Sudamericana — Fecha 2','Estadio Pedro Bidegain','Av. Perito Moreno 5301','Buenos Aires','Buenos Aires','2025-04-16T21:30:00-03:00','San Lorenzo','Deportivo Cuenca','Copa Sudamericana',ARRAY['fútbol','copa sudamericana'],true,false,'sudamer_f2_sanlorenzo_cuenca'),
-- Fecha 3
('partido','San Lorenzo vs Santos','Copa Sudamericana — Fecha 3','Estadio Pedro Bidegain','Av. Perito Moreno 5301','Buenos Aires','Buenos Aires','2025-04-28T19:00:00-03:00','San Lorenzo','Santos','Copa Sudamericana',ARRAY['fútbol','copa sudamericana'],true,false,'sudamer_f3_sanlorenzo_santos'),
('partido','Barracas Central vs Audax Italiano','Copa Sudamericana — Fecha 3','Estadio Claypole','Av. Monteverde 5240','Buenos Aires','Buenos Aires','2025-04-28T21:00:00-03:00','Barracas Central','Audax Italiano','Copa Sudamericana',ARRAY['fútbol','copa sudamericana'],true,false,'sudamer_f3_barracas_audax'),
('partido','Riestra vs Torque','Copa Sudamericana — Fecha 3','Estadio Guillermo Laza','Av. Cruz 4435','Buenos Aires','Buenos Aires','2025-04-29T19:00:00-03:00','Riestra','Torque','Copa Sudamericana',ARRAY['fútbol','copa sudamericana'],true,false,'sudamer_f3_riestra_torque'),
('partido','Tigre vs América de Cali','Copa Sudamericana — Fecha 3','Estadio José Dellagiovanna','Av. Vergara 2880','Victoria','Buenos Aires','2025-04-30T21:30:00-03:00','Tigre','América de Cali','Copa Sudamericana',ARRAY['fútbol','copa sudamericana'],true,false,'sudamer_f3_tigre_americacali'),
-- Fecha 4
('partido','Riestra vs Grêmio','Copa Sudamericana — Fecha 4','Estadio Guillermo Laza','Av. Cruz 4435','Buenos Aires','Buenos Aires','2025-05-05T19:00:00-03:00','Riestra','Grêmio','Copa Sudamericana',ARRAY['fútbol','copa sudamericana'],true,false,'sudamer_f4_riestra_gremio'),
('partido','Barracas Central vs Olimpia','Copa Sudamericana — Fecha 4','Estadio Claypole','Av. Monteverde 5240','Buenos Aires','Buenos Aires','2025-05-06T21:00:00-03:00','Barracas Central','Olimpia','Copa Sudamericana',ARRAY['fútbol','copa sudamericana'],true,false,'sudamer_f4_barracas_olimpia'),
-- Fecha 5
('partido','River Plate vs Bragantino','Copa Sudamericana — Fecha 5','Estadio Monumental','Av. Figueroa Alcorta 7597','Buenos Aires','Buenos Aires','2025-05-20T21:30:00-03:00','River Plate','RB Bragantino','Copa Sudamericana',ARRAY['fútbol','copa sudamericana'],true,false,'sudamer_f5_river_bragantino'),
('partido','Racing vs Caracas','Copa Sudamericana — Fecha 5','Estadio Juan Domingo Perón','Av. Galicia 2070','Avellaneda','Buenos Aires','2025-05-21T21:00:00-03:00','Racing Club','Caracas FC','Copa Sudamericana',ARRAY['fútbol','copa sudamericana'],true,false,'sudamer_f5_racing_caracas'),
-- Fecha 6
('partido','San Lorenzo vs Recoleta FC','Copa Sudamericana — Fecha 6','Estadio Pedro Bidegain','Av. Perito Moreno 5301','Buenos Aires','Buenos Aires','2025-05-26T21:30:00-03:00','San Lorenzo','Recoleta FC','Copa Sudamericana',ARRAY['fútbol','copa sudamericana'],true,false,'sudamer_f6_sanlorenzo_recoleta'),
('partido','Racing vs Ind. Petrolero','Copa Sudamericana — Fecha 6','Estadio Juan Domingo Perón','Av. Galicia 2070','Avellaneda','Buenos Aires','2025-05-27T19:00:00-03:00','Racing Club','Independiente Petrolero','Copa Sudamericana',ARRAY['fútbol','copa sudamericana'],true,false,'sudamer_f6_racing_petrolero'),
('partido','River Plate vs Blooming','Copa Sudamericana — Fecha 6','Estadio Monumental','Av. Figueroa Alcorta 7597','Buenos Aires','Buenos Aires','2025-05-27T21:30:00-03:00','River Plate','Blooming','Copa Sudamericana',ARRAY['fútbol','copa sudamericana'],true,false,'sudamer_f6_river_blooming'),
('partido','Tigre vs Alianza Atlético','Copa Sudamericana — Fecha 6','Estadio José Dellagiovanna','Av. Vergara 2880','Victoria','Buenos Aires','2025-05-28T21:30:00-03:00','Tigre','Alianza Atlético','Copa Sudamericana',ARRAY['fútbol','copa sudamericana'],true,false,'sudamer_f6_tigre_alianza')

ON CONFLICT (external_id) DO NOTHING;
